server:
  port: 8080
  connection-timeout: 60000
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - application/xml
      - application/xhtml+xml
      - text/html
      - text/xml
      - text/plain

spring:
  application:
    name: campsite
  datasource:
    url: jdbc:h2:mem:campsitedb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      naming_strategy:
    show-sql: false  
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: NON_NULL